/* Family review synchronization. The family passphrase is NEVER stored in this public source. */
(function(){
'use strict';
const API='https://digvzsrjqdtraerysngd.supabase.co/functions/v1/family-reviews';
const CODE_KEY='taiwan-trip-family-code-v1';
const IMPORT_KEY='taiwan-trip-family-imported-v1';
const OLD_KEY='taiwan-trip-reviews-v2';
const PEOPLE=['パパ','ママ','さき','まゆ'];
const LABELS={again:'◎',good:'○',skip:'△'};
let code='',connected=false,busy=false,memoTimers=new Map(),ratingMap=new Map(),memoMap=new Map();
try{code=localStorage.getItem(CODE_KEY)||''}catch(e){}
const status=()=>document.getElementById('family-review-message');
function message(text,bad=false){const s=status();if(s){s.textContent=text;s.style.color=bad?'#b91c1c':'#065f46'}}
function readLocal(){try{return JSON.parse(localStorage.getItem(OLD_KEY)||'{}')}catch(e){return {}}}
function storeLocal(id,patch){try{const all=readLocal();all[id]={...(all[id]||{}),...patch};localStorage.setItem(OLD_KEY,JSON.stringify(all))}catch(e){}}
async function api(method,body){const res=await fetch(API,{method,headers:{'x-family-code':code,...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{}),cache:'no-store'});let data;try{data=await res.json()}catch(e){throw Error('サーバーからの応答を確認できません')};if(!res.ok)throw Error(data.error||'通信エラー');return data}
function localImport(){const source=readLocal(),ratings=[],memos=[];for(const [review_id,record] of Object.entries(source)){if(typeof review_id!=='string'||review_id.length>300||!record||typeof record!=='object')continue;for(const person of PEOPLE){const rating=record.ratings?.[person];if(['again','good','skip'].includes(rating))ratings.push({review_id,person,rating})}if(typeof record.memo==='string'&&record.memo.trim())memos.push({review_id,memo:record.memo.slice(0,2000)})}return {action:'import',ratings,memos}}
function refreshUI(){document.querySelectorAll('.visitbox').forEach(box=>{const wrap=box.querySelector('[data-rating]');if(!wrap)return;const id=decodeURIComponent(wrap.dataset.rating||'');const found=ratingMap.get(id)||{};const button=box.querySelector('[data-visit]');if(button){button.textContent='👨‍👩‍👧‍👧 みんなの評価を見る・更新';button.classList.add('done')}
 wrap.classList.add('show');wrap.querySelectorAll('.personrow').forEach(row=>{const person=row.dataset.person;const val=found[person]||'';row.querySelectorAll('.ratebtn').forEach(btn=>{const active=btn.dataset.rate===val;btn.classList.toggle('active',active);btn.setAttribute('aria-pressed',active?'true':'false')})});
 let summary=box.querySelector('.shared-summary');if(!summary){summary=document.createElement('div');summary.className='shared-summary';summary.style.cssText='font-size:12px;margin:5px 0 3px;font-weight:700;color:#065f46';button?.insertAdjacentElement('afterend',summary)}summary.textContent=PEOPLE.map(p=>p+' '+(LABELS[found[p]]||'未評価')).join(' ／ ');
 const memo=box.querySelector('[data-memo]');if(memo){memo.classList.add('show');if(document.activeElement!==memo)memo.value=memoMap.get(id)||''}box.querySelector('.photobox')?.classList.add('show');
 });}
async function sync(show=true){if(!code)return false;try{const result=await api('GET');if(!sessionStorage.getItem(IMPORT_KEY)){const old=localImport();if(old.ratings.length||old.memos.length){await api('POST',old)}sessionStorage.setItem(IMPORT_KEY,'1');const refreshed=await api('GET');result.ratings=refreshed.ratings;result.memos=refreshed.memos}ratingMap=new Map();memoMap=new Map();(result.ratings||[]).forEach(r=>{if(!ratingMap.has(r.review_id))ratingMap.set(r.review_id,{});ratingMap.get(r.review_id)[r.person]=r.rating});(result.memos||[]).forEach(r=>memoMap.set(r.review_id,r.memo));connected=true;refreshUI();if(show)message('家族4人の評価を共有中。ほかのスマホの評価も表示しています。');return true}catch(err){connected=false;message('共有先に接続できません：'+err.message,true);if(String(err.message).includes('合言葉')){code='';try{localStorage.removeItem(CODE_KEY)}catch(e){}}return false}}
async function connect(){if(busy)return false;if(!code){const entered=window.prompt('家族共通の合言葉を入力してください。最初の1回だけで大丈夫です。');if(!entered)return false;code=entered.trim()}busy=true;message('家族の評価を読み込んでいます…');const ok=await sync();busy=false;if(ok){try{localStorage.setItem(CODE_KEY,code)}catch(e){}}return ok}
function persist(id,patch){storeLocal(id,patch)}
async function saveRating(button){if(!connected&&!(await connect()))return;const row=button.closest('.personrow'),wrap=button.closest('[data-rating]');if(!row||!wrap)return;const review_id=decodeURIComponent(wrap.dataset.rating||''),person=row.dataset.person,rating=button.dataset.rate;if(!PEOPLE.includes(person)||!['again','good','skip'].includes(rating))return;row.querySelectorAll('button').forEach(x=>x.disabled=true);message(person+'の評価を保存中…');try{await api('POST',{action:'rating',review_id,person,rating});const local=readLocal()[review_id]||{};persist(review_id,{visited:true,ratings:{...(local.ratings||{}),[person]:rating}});await sync(false);message(person+'の評価を保存しました。全員のスマホで確認できます。')}catch(err){message('評価を保存できませんでした：'+err.message,true)}finally{row.querySelectorAll('button').forEach(x=>x.disabled=false)}}
function saveMemo(input){const review_id=decodeURIComponent(input.dataset.memo||'');const memo=input.value;persist(review_id,{visited:true,memo});clearTimeout(memoTimers.get(review_id));memoTimers.set(review_id,setTimeout(async()=>{if(!connected&&!(await connect()))return;message('メモを保存中…');try{await api('POST',{action:'memo',review_id,memo});memoMap.set(review_id,memo);message('メモを家族で共有しました。')}catch(err){message('メモを共有できませんでした。入力内容はこの端末に残っています：'+err.message,true)}},700))}
function setup(){const bar=document.createElement('div');bar.style.cssText='background:#ecfdf5;border:1px solid #6ee7b7;border-radius:12px;padding:11px 12px;margin:8px 0;display:flex;gap:9px;flex-wrap:wrap;align-items:center;justify-content:space-between';bar.innerHTML='<div><strong style="font-size:13px">👨‍👩‍👧‍👧 家族の評価共有</strong><div id="family-review-message" role="status" style="font-size:12px;margin-top:4px;color:#065f46">家族共通の合言葉で接続すると、4人の評価を見られます。</div></div><button id="family-review-connect" type="button" style="background:#047857;color:#fff;border:0;border-radius:9px;padding:10px;font-weight:700;cursor:pointer">共有を開く・更新</button>';const drink=document.querySelector('.drinkbar');if(drink)drink.insertAdjacentElement('afterend',bar);else document.getElementById('app')?.prepend(bar);bar.querySelector('button').addEventListener('click',async()=>{if(!code)await connect();else await sync()});
 document.addEventListener('click',async ev=>{const target=ev.target;if(!(target instanceof Element))return;const rate=target.closest('.familyratings .ratebtn');if(rate){ev.preventDefault();ev.stopImmediatePropagation();await saveRating(rate);return}const visit=target.closest('[data-visit]');if(visit){ev.preventDefault();ev.stopImmediatePropagation();if(!connected){await connect()}else{await sync()}return}},true);
 document.addEventListener('input',ev=>{const target=ev.target;if(!(target instanceof Element))return;const memo=target.closest('[data-memo]');if(memo){ev.stopImmediatePropagation();saveMemo(memo)}},true);
 if(code)sync();
 document.addEventListener('visibilitychange',()=>{if(!document.hidden&&connected)sync(false)});
 setInterval(()=>{if(connected&&!document.hidden)sync(false)},30000);
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',setup);else setup();
})();